services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/twelveClient
      - /twelveClient/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
volumes:
  postgres: ~
